name: Development Auto Deploy to AWS S3

on:
  push:
    branches:
      - feature/fetch_data

jobs:
  deploy:
    name: Deploy Development

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Build
        run: |
          yarn install
          echo "DATA_URL=${DATA_BASE_URL}" >> .env.production
          cat .env.production
          yarn run generate:deploy --fail-on-page-error
        env:
          DATA_BASE_URL: ${{ secrets.COVID_DATA_STAGING_BASE_URL }}

      - name: Copy to s3
        run: |
          aws s3 cp ./dist ${{ secrets.AWS_SECRET_COVID_S3_DEV_PATH }} --recursive --acl public-read
