name: Statging Auto Deploy to AWS S3

on:
  push:
    branches:
      - staging-shizuoka

jobs:
  deploy:
    name: Deploy Staging

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Build
        run: |
          yarn install
          yarn run generate:deploy --fail-on-page-error

      - name: Copy to s3
        run: |
          aws s3 cp ./dist ${{ secrets.AWS_SECRET_COVID_S3_STAGING_PATH }} --recursive --acl public-read
